#!/bin/bash
clear
if [ "${EUID}" -ne 0 ]; then
echo "You need to run this script as root"
exit 1
fi
#Warna---------------------------------------
Red='\e[1;31m' #${Red}
Gray='\e[1;30' #${Gray}
Green='\e[1;32' #${Green}
Yellow='\e[1;33' #${Yellow}
Blue='\e[1;34' #${Blue}
Purple='\e[1;35' #${Purple}
Cyan='\e[1;36' #${Cyan}
White='\e[1;37' #${White}
NC='\e[0m' #${NC}

MYIP=$(wget -qO- icanhazip.com);
echo -e "${Cyan}Checking VPS...${NC}"
echo ""
sleep 3s
IZIN=$( curl https://raw.githubusercontent.com/rockneters/jancuk/main/module/izin | grep $MYIP )
if [ $MYIP = $IZIN ]; then
echo -e "${Green}Permintaan Diterima...${NC}"
else
echo -e "${Red}Permintaan Ditolak!${NC}";
echo -e "${White}Hubungi Telegram Admin : @RocknetStore!${NC}"
fi

echo -e "$MYIP" >/etc/IP
ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime >/dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1

rm -r /etc/v2ray
mkdir /etc/v2ray
rm -r  /var/lib/rocknet
mkdir /var/lib/rocknet
clear
cd

#AnimasiLoading----------------------------------------
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\${Cyan}[!] ${White}Waiting... ${Red}["
while true; do
   for((i=0; i<15; i++)); do
   echo -ne "${Yellow}#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "${Red}]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\${Cyan}[!] ${White}Waiting... ${Red}["
done
echo -e "${Red}] ${Green} OK !${NS}"
tput cnorm
}

#Header----------------------------------------------------
clear
clear
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;32m               ROCKNETSSH MANAGER                   \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;33mAUTOSCRIPT INI DI EDIT KEMBALI OLEH ADMIN ROCKNETVPN\033[0m"
echo -e "\033[1;33m MASIH DALAM PENGEMBANGAN UNTUK HASIL YANG SEMPURNA \033[0m"
echo -e "\033[1;33m   ANDA DAPAT MEMBUAT USER AKUN LEWAT BOT TELEGRAM  \033[0m"
echo -e "\033[1;33m     DAN MEMANAGEMENT AKUN DENGAN SANGAT MUDAH!     \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;33m   INFO LEBIH LANJUT HUB. TELEGRAM: @RocknetStore   \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
read -p "$(echo -e "\033[1;36mAPAKAH INGIN MELANJUTKAN ? \033[1;33m[y/N]:\033[0m")" -e -i y resp
[[ $resp = @(n|N) ]] && rm $HOME/Rocknet && exit 0
cp /etc/ssh/sshd_config /etc/ssh/sshd_back
wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/rockneters/jancuk/main/module/sshd_config > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
sleep 3s

[[ ! -d /etc/SSHPlus ]] && mkdir /etc/SSHPlus
[[ ! -d /etc/SSHPlus/senha ]] && mkdir /etc/SSHPlus/senha
[[ ! -e /etc/SSHPlus/Exp ]] && touch /etc/SSHPlus/Exp
[[ ! -d /etc/SSHPlus/userteste ]] && mkdir /etc/SSHPlus/userteste
[[ ! -d /etc/SSHPlus/.tmp ]] && mkdir /etc/SSHPlus/.tmp
[[ ! -d /etc/bot ]] && mkdir /etc/bot
[[ ! -d /etc/bot/info-users ]] && mkdir /etc/bot/info-users
[[ ! -d /etc/bot/arquivos ]] && mkdir /etc/bot/arquivos
[[ ! -d /etc/bot/revenda ]] && mkdir /etc/bot/revenda
[[ ! -d /etc/bot/suspensos ]] && mkdir /etc/bot/suspensos
[[ ! -e /etc/bot/lista_ativos ]] && touch /etc/bot/lista_ativos
[[ ! -e /etc/bot/lista_suspensos ]] && touch /etc/bot/lista_suspensos

echo -e 'by: @RocknetStore' >/usr/lib/sshplus
cat /usr/lib/sshplus > /etc/SSHPlus/.tmp/crazy
netstat -nplt | grep -w 'apache2' | grep -w '80'
sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf
service apache2 restart

[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]]
sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config
service ssh restart

grep -v "^PasswordAuthentication" /etc/ssh/sshd_config >/tmp/passlogin
mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
_dir1='/bin'
_dir2='/etc/SSHPlus'
rm $_dir2/ShellBot.sh $_dir2/cabecalho $_dir2/open.py $_dir2/proxy.py >/dev/null 2>&1
_mdls=("addhost" "delhost" "alterarsenha" "criarusuario" "expcleaner" "mudardata" "remover" "criarteste" "verifbot" "droplimiter" "alterarlimite" "ajuda" "sshmonitor" "badvpn" "userbackup" "instsqd" "blockt" "otimizar" "menu" "speedtest" "banner" "senharoot" "reiniciarservicos" "reiniciarsistema" "attscript" "conexao" "delscript" "detalhes" "botssh" "infousers" "slow_dns" "verifatt" "limiter" "uexpired" "cabecalho" "bot" "open.py" "proxy.py")
for _arq in ${_mdls[@]}; do
	[[ -e $_dir1/$_arq ]] && rm $_dir1/$_arq >/dev/null 2>&1
	wget -c -P $_dir1 https://raw.githubusercontent.com/rockneters/jancuk/main/module/$_arq
	chmod +x $_dir1/$_arq
done
mv $_dir1/cabecalho $_dir1/bot $_dir1/open.py $_dir1/proxy.py $_dir2
_arq_host="/etc/hosts"
_host[0]="d1n212ccp6ldpw.cloudfront.net"
_host[1]="dns.whatsapp.net"
_host[2]="portalrecarga.vivo.com.br/recarga"
_host[3]="navegue.vivo.com.br/controle/"
_host[4]="navegue.vivo.com.br/pre/"
_host[5]="www.whatsapp.net"
_host[6]="/SSHPLUS?"
for host in ${_host[@]}; do
	if [[ "$(grep -w "$host" $_arq_host | wc -l)" = "0" ]]; then
		sed -i "3i\127.0.0.1 $host" $_arq_host
	fi
done
[[ ! -e /etc/autostart ]] && {
	echo '#!/bin/bash
clear
#INICIO AUTOMATICO' >/etc/autostart
	chmod +x /etc/autostart
} || {
	[[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/rockneters/jancuk/main/module/ShellBot.sh >/etc/SSHPlus/ShellBot.sh
	for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
		screen -r -S "$proc" -X quit
	done
	screen -wipe >/dev/null
	echo '#!/bin/bash
clear
#INICIO AUTOMATICO' >/etc/autostart
	chmod +x /etc/autostart
}
crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "@daily /bin/verifatt"
	echo "@reboot /etc/autostart"
	echo "* * * * * /etc/autostart"
	echo "0 */6 * * * /bin/uexpired"
) | crontab -

wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 >/dev/null 2>&1
chmod +x jq-linux64 && mv jq-linux64 $(which jq)
service cron restart >/dev/null 2>&1
service ssh restart >/dev/null 2>&1
[[ -d /var/www/html/openvpn ]] && service apache2 restart >/dev/null 2>&1
clear
sleep 3s
#--------------------------------------------------------
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
echo "apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/rockneters/jancuk/main/Rocknet; chmod 777 Rocknet; ./Rocknet" > /bin/sshplus; chmod +x /bin/sshplus > /dev/null 2>&1
cd
wget -O /bin/menu https://raw.githubusercontent.com/rockneters/jancuk/main/module/menu > /dev/null 2>&1; chmod +x /bin/menu
wget -O /bin/menuV1 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV1 > /dev/null 2>&1; chmod +x /bin/menuV1
wget -O /bin/menuV2 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV2 > /dev/null 2>&1; chmod +x /bin/menuV2
wget -O /bin/menuV3 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV3 > /dev/null 2>&1; chmod +x /bin/menuV3
wget -O /bin/menuV4 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV4 > /dev/null 2>&1; chmod +x /bin/menuV4
clear

#Database------------------------------------------------------------------------
echo -e "${Cyan}[Information] ${White}Checking Database....${NC}"
sleep 3s
[[ -f "$HOME/usuarios.db" ]] && {
    echo -e "========================================================"
    echo -e "${Red}Database user telah ditemukan !!${NC}"
    echo -e "${Red}Apakah akan menggunakan Database lama atau membuat baru?${NC}" 
	echo -e "${Cyan}[1] ${White}Menggunakan Database lama${NC}"
	echo -e "${Cyan}[2] ${White}Membuat Database baru${NC}"
	echo -e "========================================================"
    echo ""
	read -p "Option?: " -e -i 1 optiondb
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear

#Installing------------------------------------------------------------------------
echo -e "========================================================"
echo -e "${White}|               • WAIT FOR INSTALLATION •               |${NC}"
echo -e "========================================================"
echo ""
echo -e "${Cyan}[!] ${White}UPDATING SYSTEM ${Cyan}[!]${NC}"
fun_attlist () {
    apt-get update -y
	[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
	echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'

echo ""
echo -e "${Cyan}[!] ${White}INSTALL PACKAGE ${Cyan}[!]${NC}"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "screen" "net-tools" "dos2unix" "nload" "jq" "figlet" "python3" "python-pip" "ufw")
for _prog in ${_pacotes[@]}; do
    apt install $_prog -y
done
[[ -f "/etc/default/ufw" ]] && ufw allow 443/tcp; ufw allow 80/tcp; ufw allow 3128/tcp; ufw allow 8799/tcp; ufw allow 8080/tcp; ufw allow 7100:7300/tcp
pip install speedtest-cli
}
fun_bar 'inst_pct'

clear
echo -e "${Cyan}[!] ${White}INSTALL ALL SERVICE ${Cyan}[!]${NC}"
echo ""
sleep 5s
echo -e "${Cyan}[!] ${White}INSTALL OVPN ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ssh-vpn.sh; chmod +x ssh-vpn.sh; ./ins-vpn.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL WEBSOCKET ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/websocket-python/websocket.sh && chmod +x websocket.sh && screen -S websocket.sh ./websocket.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL V2RAY ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-vt.sh; chmod +x ins-vt.sh; sed -i -e 's/\r$//' ins-vt.sh; ./ins-vt.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL SSR ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ssr.sh; chmod +x ins-ssr.sh; ./ins-ssr.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL SSTP ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-sstp.sh; chmod +x ins-sstp.sh; ./ins-sstp.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL TCP TWEAKER ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-tcptweaker.sh; chmod +x ins-tcptweaker.sh; ./ins-tcptweaker.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL WEBMIN ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-webmin.sh; chmod +x ins-webmin.sh; ./ins-webmin.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL WIREGUARD ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-wg.sh; chmod +x ins-wg.sh; ./ins-wg.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL WIREGUARD ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ipsec.sh; chmod +x ins-ipsec.sh; ./ins-ipsec.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL SHADOWSOCK ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ssobfs.sh; chmod +x ins-ssobfs.sh; ./ins-ssobfs.sh
clear
echo -e "${Cyan}[!] ${White}INSTALL MENU ${Cyan}[!]${NC}"
wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-menu.sh; chmod +x ins-menu.sh; ./ins-menu.sh

clear
echo -e "\033[1;33m[!] \033[1;32mFINISHING \033[1;33m[!]\033[0m"
echo -e "\033[1;33mCOMPLETING FUNCTIONS AND SETTINGS! \033[0m"
echo ""
sleep3
cd $HOME
echo -e "\033[1;33m • \033[1;32mINSTALLATION COMPLETED\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mMAIN COMMAND: \033[1;32mmenu\033[0m"
echo ""
cd
rm Rocknet ssh-vpn.sh ins-ssr.sh ins-sstp.sh ins-tcptweaker.sh ins-webmin.sh ins-vt.sh ins-wg.sh ins-badvpn.sh ins-ipsec.sh ins-ssobfs.sh ins-menu.sh 
cat /dev/null > ~/.bash_history && history -c