#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- \033[1;33mAnda harus login sebagai root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
GitUser="https://raw.githubusercontent.com/rockneters/jancuk/main"
cd $HOME
echo "Update & Install Aplikasi Pendukung..."
sleep 1s
apt update -y; apt upgrade -y; apt install wget curl

#Loading animasi----------------------------------------
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33mHOLD \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<25; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33mHOLD \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

#Validasi Key---------------------------------------------
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
  echo -e "\n\033[1;31mINVALID KEY!\033[0m"
  rm -rf $HOME/Plus > /dev/null 2>&1
  sleep 2
  clear; exit 1
}
}

#Header----------------------------------------------------
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;32m               ROCKNETSSH MANAGER                   \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;33mAUTOSCRIPT INI DI EDIT KEMBALI OLEH ADMIN ROCKNETVPN\033[0m"
echo -e "\033[1;33m MASIH DALAM PENGEMBANGAN UNTUK HASIL YANG SEMPURNA \033[0m"
echo -e "\033[1;33m   ANDA DAPAT MEMBUAT USER AKUN LEWAT BOT TELEGRAM  \033[0m"
echo -e "\033[1;33m     DAN MEMANAGEMENT AKUN DENGAN SANGAT MUDAH!     \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;33m   INFO LEBIH LANJUT HUB. TELEGRAM: @RocknetStore   \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

#-----------------------------------------------------------------------------------------------------------------
read -p "$(echo -e "\033[1;36mAPAKAH INGIN MELANJUTKAN ? \033[1;33m[y/N]:\033[0m")" -e -i y resp
[[ $resp = @(n|N) ]] && rm $HOME/Plus && exit 0
cp /etc/ssh/sshd_config /etc/ssh/sshd_back
wget -O /etc/ssh/sshd_config ${GitUser}/module/sshd_config > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\033[1;36mChecking Permission....\033[0m" 
verif_key
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
echo "apt-get update -y; apt-get upgrade -y; wget ${GitUser}/Plus; chmod 777 Plus; ./Plus" > /bin/sshplus; chmod +x /bin/sshplus > /dev/null 2>&1
wget -O /bin/menu ${GitUser}/module/menu > /dev/null 2>&1; chmod +x /bin/menu
clear

#Database------------------------------------------------------------------------
echo -e "\033[1;36mChecking Database....\033[0m"
sleep 3s
[[ -f "$HOME/usuarios.db" ]] && {
    echo -e "\033[0;34m========================================================\033[0m"
    echo -e "\033[1;33mDatabase user telah ditemukan !!\033[0m"
    echo -e "\033[1;33mApakah akan menggunakan Database lama atau membuat baru?\033[0m" 
	echo -e "\033[1;37m[1] \033[1;33mMenggunakan Database lama\033[0m"
	echo -e "\033[1;37m[2] \033[1;33mMembuat Database baru\033[0m"
	echo -e "\033[0;34m========================================================\033[0m"
    echo ""
	read -p "Option?: " -e -i 1 optiondb
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear

#Installing------------------------------------------------------------------------
echo -e "\033[0;34m========================================================\033[0m"
echo -e "\033[1;33m|                WAIT FOR INSTALLATION                 |\033[0m"
echo -e "\033[0;34m========================================================\033[0m"
echo ""
echo -e "\033[1;33m[!] \033[1;32mUPDATING SYSTEM \033[1;33m[!]\033[0m"
echo -e "\033[1;33m===-MEMBUTUHKAN WAKTU BEBERAPA MENIT!-===\033[0m"
echo ""
fun_attlist () {
    apt-get update -y
	[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
	echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'

echo ""
echo -e "\033[1;33m[!] \033[1;32mINSTALL PACKAGE \033[1;33m[!]\033[0m"echo ""
echo -e "\033[1;33m===-MEMBUTUHKAN WAKTU LEBIH LAMA!-===\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "screen" "net-tools" "dos2unix" "nload" "jq" "figlet" "python3" "python-pip" "ufw")
for _prog in ${_pacotes[@]}; do
    apt install $_prog -y
done
ufw enable
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/etc/default/ufw" ]] && ufw allow 443/tcp; ufw allow 80/tcp; ufw allow 3128/tcp; ufw allow 8799/tcp; ufw allow 8080/tcp; ufw allow 7100:7300/tcp
clear
echo -e "\033[1;33m[!] \033[1;32mINSTALL ALL SERVICE \033[1;33m[!]\033[0m"
echo -e "\033[1;33m===-TUNGGULAH SAMPAI 5-10 MENIT!-=== \033[0m"
echo ""
sleep 5
wget ${GitUser}/install/ssh-vpn.sh; chmod +x ssh-vpn.sh; screen -S ssh-vpn ./ssh-vpn.sh
wget ${GitUser}/install/ins-ssr.sh; chmod +x ins-ssr.sh; screen -S ins-ssr ./ins-ssr.sh
wget ${GitUser}/install/ins-sstp.sh; chmod +x ins-sstp.sh; screen -S ins-sstp ./ins-sstp.sh
wget ${GitUser}/install/ins-tcptweaker.sh; chmod +x ins-tcptweaker.sh; screen -S ins-tcptweaker ./ins-tcptweaker.sh
wget ${GitUser}/install/ins-webmin.sh; chmod +x ins-webmin.sh; screen -S ins-webmin ./ins-webmin.sh
wget ${GitUser}/install/ins-vt.sh; chmod +x ins-vt.sh; screen -S ins-vt ./ins-vt.sh
wget ${GitUser}/install/ins-wg.sh; chmod +x ins-wg.sh; screen -S ins-wg ./ins-wg.sh
wget ${GitUser}/install/ins-badvpn.sh; chmod +x ins-badvpn.sh; screen -S ins-badvpn ./ins-badvpn.sh
wget ${GitUser}/install/ins-go.sh; chmod +x ins-go.sh; screen -S ins-go ./ins-go.sh
wget ${GitUser}/install/ins-ipsec.sh; chmod +x ins-ipsec.sh; screen -S ins-ipsec ./ins-ipsec.sh
wget ${GitUser}/install/ins-ssobfs.sh; chmod +x ins-ssobfs.sh; screen -S ins-ssobfs ./ins-ssobfs.sh
wget ${GitUser}/install/ins-menu.sh; chmod +x ins-menu.sh; screen -S ins-menu ./ins-menu.sh

clear
echo -e "\033[1;33m[!] \033[1;32mFINISHING \033[1;33m[!]\033[0m"
echo -e "\033[1;33mCOMPLETING FUNCTIONS AND SETTINGS! \033[0m"
echo ""
sleep3
#fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
echo ""
cd $HOME
echo -e "\033[1;33m • \033[1;32mINSTALLATION COMPLETED\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mMAIN COMMAND: \033[1;32mmenu\033[0m"
echo ""
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
